version: "3.4"

services:
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    image: ui
    restart: "no"
    volumes:
      - ./ui/:/app
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file:
      - project.env
    networks:
      - bridge

  api:
    build: api
    image: api
    restart: "always"
    volumes:
      - ./api/:/usr/app
    ports:
      - 4000:4000
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    networks:
      - bridge

  database:
    container_name: dab-p3-database
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env
    networks:
      - bridge

  flyway:
    container_name: flyway
    image: flyway/flyway:8.4.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
