apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: pgpass
                  optional: false
