apiVersion: batch/v1
kind: Job
metadata:
  name: my-database-migration-job
spec:
  template:
    metadata:
      name: my-database-migration
    spec:
      containers:
        - name: my-flyway-migrations
          image: flyway
          imagePullPolicy: Never
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: username
                  optional: false
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-database-cluster-app
                  key: password
                  optional: false
      # as its a migration job, we do not want to restart it
      restartPolicy: Never
  backoffLimit: 2
